### ISSUE TITLE
still active

### ISSUE THREAD

**Issue by kevinsoltis41** [AnthoneyKalasho/MlbTheShow16MarketAssistant#1]
Hey I just found this via theshownation forum.
Are you still working on this? I was hoping to do stuff with it 

-Kevin

**Comment by AnthoneyKalasho** [comment]
I've been a little busy with school but thats going to be wrapping up soon. I do plan to continue working on it but I'm not exactly sure where I would like to go from here. What were you planning on doing?

**Comment by kevinsoltis41** [comment]
I did mine Web Based so that people didn't have to download, just navigate to the URL.
- I also wanted to be able to link up someone's inventory with the data from the Community Market for a more 'live' feel of their Items.

Sound like something worth doing?
Any specific reason why you chose .java w/ .swing.\* ?

I might be faster via Email: kevinsoltis41@gmail.com if you want to continue it there.

**Comment by kevinsoltis41** [comment]
We can also leverage the data from the bottom graph to do something with the history of the bids.

IE. http://theshownation.com/market/details?id=17453
